//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod categories;
pub mod comments;
pub mod posts;
pub mod users;


pub use users::Entity as Users;
pub use categories::Entity as Categories;
pub use posts::Entity as Posts;
pub use comments::Entity as Comments;